### PR TITLE
Do not `JSON.stringify` a stream body

### PR DESCRIPTION
**Pull request by emilbayes**
Allow the use of streams while decoding the response as json

### CODE REVIEW

**Comment by bendrucker** [comment]
Take a look at the test failure please, you'll need to add a truthiness check to either your expression or `isStream`.

**Comment by emilbayes** [comment]
Sorry, I was a bit too quick there. Did run tests locally, but should have copy/pasted. You can squash if you're happy as is now :)

**Comment by emilbayes** [comment]
@bendrucker In this case truthyness is guaranteed by the `if (opts.body)` :)

**Comment by bendrucker** [comment]
Oh right just a typo

**Comment by bendrucker** [comment]
This looks ok to me, I'll wait a bit and see if feross would like to merge or wants a test

**Comment by emilbayes** [comment]
Great :+1: Very quick turnaround!

**Comment by feross** [comment]
I added a test in commit https://github.com/feross/simple-get/commit/71646396cb225727bd79ec435ff495b2bb5b33cc and released as 2.6.1.

**Comment by feross** [comment]
@emilbayes I also added you as a collaborator to this repo.

**Comment by emilbayes** [comment]
Thank you!

**Pull request merged**
