### PR TITLE
feat: do not follow redirects and do not error out

### PR DESCRIPTION
**Pull request by alessioalex**
Use cases:

- Black friday online shops, get notified when they are up 

- New releases for game web applications, such as Fifa 19

- etc

### CODE REVIEW

**Comment by alessioalex** [comment]
@mcollina done!

**Comment by alessioalex** [comment]
ping @feross

**Comment by SebastianSchmidt** [comment]
I don't think this feature should be added. So far this module focuses on the essential features - matching the name "simple-get". This new feature is only useful for special use cases. If at some point all imaginable use cases are supported, this module has probably lost its wonderful simplicity.

**Comment by alessioalex** [comment]
I think this is a valid and simple use case. Furthermore the change only adds an extra condition (34 chars) to an if statement. I don't think the module should automatically follow redirects no matter the situation.

**Comment by alessioalex** [comment]
ping @feross

**Comment by millette** [comment]
What about calling it with

```js
get({url, maxRedirects: 0}, cb)
```

Maybe just a matter of documentating `maxRedirects` ?

**Comment by feross** [comment]
@millette Nice idea to use `get({url, maxRedirects: 0}, cb)` but an error is thrown when too many redirects have happened, so this just throws an error instead of allowing the user to see the response.

@alessioalex Thanks for the PR, this looks good to me.

**Comment by feross** [comment]
3.1.0

**Comment by alessioalex** [comment]
thanks @feross

**Pull request merged**
